import type { Metadata } from "next";

//import { Geist, Geist_Mono } from "next/font/google";

import { CartProvider } from "./context/CartContext";
import "./globals.css";
import LayoutClient from "./layoutClient";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Facebook",
  description: "Generated by create next app",
  icons:{
    icon:"/favicon.png"
  }
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body //className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white `}>
          className="antialiased bg-white">

        <CartProvider>
            <LayoutClient>{children}</LayoutClient>
        </CartProvider>
      </body>
    </html>
  );

}

